[package]
name = "vulkan-layer-capture"
edition = "2021"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "VkLayer_wallpiper_capture"

[[bin]]
name = "receiver"
path = "src/bin/receiver.rs"
required-features = ["dev-tools"]

[[bin]]
name = "dmabuf_source_test"
path = "src/bin/dmabuf_source_test.rs"
required-features = ["dev-tools"]

[features]
dev-tools = []

[dependencies]
ash = "0.37.3"
libc = "0.2"
nix = { version = "0.29", features = ["socket", "uio"] }
vulkan-layer = { path = "../vulkan-layer" }
