[package]
name = "wallpiper-portal-i3"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wallpiper-portal-i3"
path = "src/main.rs"

[dependencies]
wallpiper-protocol = { path = "../crates/wallpiper-protocol" }
serde_json = "1"
x11rb = { version = "0.13", features = ["dri3", "shm", "allow-unsafe-code"] }
libc = "0.2"
